const SECONDARY_ANALYSES = 'secondaryAnalyses';

const SECONDARY_ANALYSES_CREATED = `${SECONDARY_ANALYSES}/created`;
const SECONDARY_ANALYSES_LOADING = `${SECONDARY_ANALYSES}/loading`;
const SECONDARY_ANALYSES_LOADED = `${SECONDARY_ANALYSES}/loaded`;
const SECONDARY_ANALYSES_ERROR = `${SECONDARY_ANALYSES}/error`;
const SECONDARY_ANALYSES_SAVING = `${SECONDARY_ANALYSES}/saving`;
const SECONDARY_ANALYSES_SET_ACTIVE = `${SECONDARY_ANALYSES}/setActive`;
const SECONDARY_ANALYSES_DELETED = `${SECONDARY_ANALYSES}/deleted`;
const SECONDARY_ANALYSES_UPDATED = `${SECONDARY_ANALYSES}/updated`;

export {
  SECONDARY_ANALYSES_CREATED,
  SECONDARY_ANALYSES_LOADING,
  SECONDARY_ANALYSES_LOADED,
  SECONDARY_ANALYSES_ERROR,
  SECONDARY_ANALYSES_SAVING,
  SECONDARY_ANALYSES_SET_ACTIVE,
  SECONDARY_ANALYSES_DELETED,
  SECONDARY_ANALYSES_UPDATED,
};
