const SECONDARY_ANALYSES = 'secondaryAnalyses';

const SECONDARY_ANALYSES_CREATED = `${SECONDARY_ANALYSES}/created`;
const SECONDARY_ANALYSES_LOADING = `${SECONDARY_ANALYSES}/loading`;
const SECONDARY_ANALYSES_LOADED = `${SECONDARY_ANALYSES}/loaded`;
const SECONDARY_ANALYSES_ERROR = `${SECONDARY_ANALYSES}/error`;
const SECONDARY_ANALYSES_CANCELLED = `${SECONDARY_ANALYSES}/cancelled`;
const SECONDARY_ANALYSES_SAVING = `${SECONDARY_ANALYSES}/saving`;
const SECONDARY_ANALYSES_SET_ACTIVE = `${SECONDARY_ANALYSES}/setActive`;
const SECONDARY_ANALYSES_DELETED = `${SECONDARY_ANALYSES}/deleted`;
const SECONDARY_ANALYSES_UPDATED = `${SECONDARY_ANALYSES}/updated`;
const SECONDARY_ANALYSES_LAUNCHED = `${SECONDARY_ANALYSES}/launched`;

const SECONDARY_ANALYSIS_FILES = 'secondaryAnalysisFiles';
const SECONDARY_ANALYSIS_FILES_LOADING = `${SECONDARY_ANALYSIS_FILES}/loading`;
const SECONDARY_ANALYSIS_FILES_LOADED = `${SECONDARY_ANALYSIS_FILES}/loaded`;
const SECONDARY_ANALYSIS_FILES_ERROR = `${SECONDARY_ANALYSIS_FILES}/error`;
const SECONDARY_ANALYSIS_FILES_UPDATE = `${SECONDARY_ANALYSIS_FILES}/update`;
const SECONDARY_ANALYSIS_FILES_CREATED = `${SECONDARY_ANALYSIS_FILES}/created`;
const SECONDARY_ANALYSIS_FILES_DELETE = `${SECONDARY_ANALYSIS_FILES}/delete`;
const SECONDARY_ANALYSIS_FILES_FASTQ_TYPE_UPDATED = `${SECONDARY_ANALYSIS_FILES}/fastqTypeUpdate`;

const SECONDARY_ANALYSIS_STATUS_LOADING = `${SECONDARY_ANALYSES}/statusLoading`;
const SECONDARY_ANALYSIS_STATUS_LOADED = `${SECONDARY_ANALYSES}/statusLoaded`;
const SECONDARY_ANALYSIS_LOGS_LOADING = `${SECONDARY_ANALYSES}/logsLoading`;
const SECONDARY_ANALYSIS_LOGS_LOADED = `${SECONDARY_ANALYSES}/logsLoaded`;

const SECONDARY_PAIR_MATCHES_UPDATED = `${SECONDARY_ANALYSES}/pairMatchesUpdated`;

export {
  SECONDARY_ANALYSES_CREATED,
  SECONDARY_ANALYSES_LOADING,
  SECONDARY_ANALYSES_LOADED,
  SECONDARY_ANALYSES_ERROR,
  SECONDARY_ANALYSES_SAVING,
  SECONDARY_ANALYSES_SET_ACTIVE,
  SECONDARY_ANALYSES_DELETED,
  SECONDARY_ANALYSES_UPDATED,
  SECONDARY_ANALYSES_LAUNCHED,
  SECONDARY_ANALYSIS_FILES_LOADING,
  SECONDARY_ANALYSIS_FILES_LOADED,
  SECONDARY_ANALYSIS_FILES_ERROR,
  SECONDARY_ANALYSIS_FILES_UPDATE,
  SECONDARY_ANALYSIS_FILES_CREATED,
  SECONDARY_ANALYSIS_FILES_DELETE,
  SECONDARY_ANALYSIS_FILES_FASTQ_TYPE_UPDATED,
  SECONDARY_ANALYSIS_STATUS_LOADING,
  SECONDARY_ANALYSIS_STATUS_LOADED,
  SECONDARY_ANALYSES_CANCELLED,
  SECONDARY_ANALYSIS_LOGS_LOADING,
  SECONDARY_ANALYSIS_LOGS_LOADED,
  SECONDARY_PAIR_MATCHES_UPDATED,
};
